/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package ltw.content.service.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

import ltw.content.service.model.LTW_content;
import ltw.content.service.model.LTW_contentModel;

/**
 * The base model implementation for the LTW_content service. Represents a row in the &quot;LTW_LTW_content&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>LTW_contentModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LTW_contentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LTW_contentImpl
 * @generated
 */
@JSON(strict = true)
public class LTW_contentModelImpl
	extends BaseModelImpl<LTW_content> implements LTW_contentModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ltw_content model instance should use the <code>LTW_content</code> interface instead.
	 */
	public static final String TABLE_NAME = "LTW_LTW_content";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"ltwId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"motorcycleName", Types.VARCHAR},
		{"motorcycleManufacturing", Types.VARCHAR},
		{"motorcycleYear", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ltwId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("motorcycleName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("motorcycleManufacturing", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("motorcycleYear", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table LTW_LTW_content (uuid_ VARCHAR(75) null,ltwId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,motorcycleName VARCHAR(75) null,motorcycleManufacturing VARCHAR(75) null,motorcycleYear INTEGER)";

	public static final String TABLE_SQL_DROP = "drop table LTW_LTW_content";

	public static final String ORDER_BY_JPQL =
		" ORDER BY ltw_content.motorcycleYear ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY LTW_LTW_content.motorcycleYear ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LTWID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long MOTORCYCLEMANUFACTURING_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long MOTORCYCLENAME_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long MOTORCYCLEYEAR_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long USERID_COLUMN_BITMASK = 64L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long USERNAME_COLUMN_BITMASK = 128L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 256L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public LTW_contentModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _ltwId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLtwId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _ltwId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return LTW_content.class;
	}

	@Override
	public String getModelClassName() {
		return LTW_content.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<LTW_content, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<LTW_content, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LTW_content, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((LTW_content)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<LTW_content, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<LTW_content, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(LTW_content)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<LTW_content, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<LTW_content, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<LTW_content, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<LTW_content, Object>>
				attributeGetterFunctions =
					new LinkedHashMap<String, Function<LTW_content, Object>>();

			attributeGetterFunctions.put("uuid", LTW_content::getUuid);
			attributeGetterFunctions.put("ltwId", LTW_content::getLtwId);
			attributeGetterFunctions.put("groupId", LTW_content::getGroupId);
			attributeGetterFunctions.put(
				"companyId", LTW_content::getCompanyId);
			attributeGetterFunctions.put("userId", LTW_content::getUserId);
			attributeGetterFunctions.put("userName", LTW_content::getUserName);
			attributeGetterFunctions.put(
				"createDate", LTW_content::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", LTW_content::getModifiedDate);
			attributeGetterFunctions.put(
				"motorcycleName", LTW_content::getMotorcycleName);
			attributeGetterFunctions.put(
				"motorcycleManufacturing",
				LTW_content::getMotorcycleManufacturing);
			attributeGetterFunctions.put(
				"motorcycleYear", LTW_content::getMotorcycleYear);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<LTW_content, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<LTW_content, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<LTW_content, ?>>();

			attributeSetterBiConsumers.put(
				"uuid", (BiConsumer<LTW_content, String>)LTW_content::setUuid);
			attributeSetterBiConsumers.put(
				"ltwId", (BiConsumer<LTW_content, Long>)LTW_content::setLtwId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<LTW_content, Long>)LTW_content::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<LTW_content, Long>)LTW_content::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<LTW_content, Long>)LTW_content::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<LTW_content, String>)LTW_content::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<LTW_content, Date>)LTW_content::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<LTW_content, Date>)LTW_content::setModifiedDate);
			attributeSetterBiConsumers.put(
				"motorcycleName",
				(BiConsumer<LTW_content, String>)
					LTW_content::setMotorcycleName);
			attributeSetterBiConsumers.put(
				"motorcycleManufacturing",
				(BiConsumer<LTW_content, String>)
					LTW_content::setMotorcycleManufacturing);
			attributeSetterBiConsumers.put(
				"motorcycleYear",
				(BiConsumer<LTW_content, Integer>)
					LTW_content::setMotorcycleYear);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getLtwId() {
		return _ltwId;
	}

	@Override
	public void setLtwId(long ltwId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ltwId = ltwId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalLtwId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("ltwId"));
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalUserId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("userId"));
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUserName() {
		return getColumnOriginalValue("userName");
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getMotorcycleName() {
		if (_motorcycleName == null) {
			return "";
		}
		else {
			return _motorcycleName;
		}
	}

	@Override
	public void setMotorcycleName(String motorcycleName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_motorcycleName = motorcycleName;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalMotorcycleName() {
		return getColumnOriginalValue("motorcycleName");
	}

	@JSON
	@Override
	public String getMotorcycleManufacturing() {
		if (_motorcycleManufacturing == null) {
			return "";
		}
		else {
			return _motorcycleManufacturing;
		}
	}

	@Override
	public void setMotorcycleManufacturing(String motorcycleManufacturing) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_motorcycleManufacturing = motorcycleManufacturing;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalMotorcycleManufacturing() {
		return getColumnOriginalValue("motorcycleManufacturing");
	}

	@JSON
	@Override
	public int getMotorcycleYear() {
		return _motorcycleYear;
	}

	@Override
	public void setMotorcycleYear(int motorcycleYear) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_motorcycleYear = motorcycleYear;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalMotorcycleYear() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("motorcycleYear"));
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(LTW_content.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), LTW_content.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public LTW_content toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, LTW_content>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LTW_contentImpl ltw_contentImpl = new LTW_contentImpl();

		ltw_contentImpl.setUuid(getUuid());
		ltw_contentImpl.setLtwId(getLtwId());
		ltw_contentImpl.setGroupId(getGroupId());
		ltw_contentImpl.setCompanyId(getCompanyId());
		ltw_contentImpl.setUserId(getUserId());
		ltw_contentImpl.setUserName(getUserName());
		ltw_contentImpl.setCreateDate(getCreateDate());
		ltw_contentImpl.setModifiedDate(getModifiedDate());
		ltw_contentImpl.setMotorcycleName(getMotorcycleName());
		ltw_contentImpl.setMotorcycleManufacturing(
			getMotorcycleManufacturing());
		ltw_contentImpl.setMotorcycleYear(getMotorcycleYear());

		ltw_contentImpl.resetOriginalValues();

		return ltw_contentImpl;
	}

	@Override
	public LTW_content cloneWithOriginalValues() {
		LTW_contentImpl ltw_contentImpl = new LTW_contentImpl();

		ltw_contentImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		ltw_contentImpl.setLtwId(this.<Long>getColumnOriginalValue("ltwId"));
		ltw_contentImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		ltw_contentImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		ltw_contentImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		ltw_contentImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		ltw_contentImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		ltw_contentImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		ltw_contentImpl.setMotorcycleName(
			this.<String>getColumnOriginalValue("motorcycleName"));
		ltw_contentImpl.setMotorcycleManufacturing(
			this.<String>getColumnOriginalValue("motorcycleManufacturing"));
		ltw_contentImpl.setMotorcycleYear(
			this.<Integer>getColumnOriginalValue("motorcycleYear"));

		return ltw_contentImpl;
	}

	@Override
	public int compareTo(LTW_content ltw_content) {
		int value = 0;

		if (getMotorcycleYear() < ltw_content.getMotorcycleYear()) {
			value = -1;
		}
		else if (getMotorcycleYear() > ltw_content.getMotorcycleYear()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof LTW_content)) {
			return false;
		}

		LTW_content ltw_content = (LTW_content)object;

		long primaryKey = ltw_content.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<LTW_content> toCacheModel() {
		LTW_contentCacheModel ltw_contentCacheModel =
			new LTW_contentCacheModel();

		ltw_contentCacheModel.uuid = getUuid();

		String uuid = ltw_contentCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			ltw_contentCacheModel.uuid = null;
		}

		ltw_contentCacheModel.ltwId = getLtwId();

		ltw_contentCacheModel.groupId = getGroupId();

		ltw_contentCacheModel.companyId = getCompanyId();

		ltw_contentCacheModel.userId = getUserId();

		ltw_contentCacheModel.userName = getUserName();

		String userName = ltw_contentCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			ltw_contentCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			ltw_contentCacheModel.createDate = createDate.getTime();
		}
		else {
			ltw_contentCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			ltw_contentCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			ltw_contentCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		ltw_contentCacheModel.motorcycleName = getMotorcycleName();

		String motorcycleName = ltw_contentCacheModel.motorcycleName;

		if ((motorcycleName != null) && (motorcycleName.length() == 0)) {
			ltw_contentCacheModel.motorcycleName = null;
		}

		ltw_contentCacheModel.motorcycleManufacturing =
			getMotorcycleManufacturing();

		String motorcycleManufacturing =
			ltw_contentCacheModel.motorcycleManufacturing;

		if ((motorcycleManufacturing != null) &&
			(motorcycleManufacturing.length() == 0)) {

			ltw_contentCacheModel.motorcycleManufacturing = null;
		}

		ltw_contentCacheModel.motorcycleYear = getMotorcycleYear();

		return ltw_contentCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<LTW_content, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<LTW_content, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LTW_content, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((LTW_content)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, LTW_content>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					LTW_content.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _ltwId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _motorcycleName;
	private String _motorcycleManufacturing;
	private int _motorcycleYear;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<LTW_content, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((LTW_content)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("ltwId", _ltwId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("motorcycleName", _motorcycleName);
		_columnOriginalValues.put(
			"motorcycleManufacturing", _motorcycleManufacturing);
		_columnOriginalValues.put("motorcycleYear", _motorcycleYear);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("ltwId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("motorcycleName", 256L);

		columnBitmasks.put("motorcycleManufacturing", 512L);

		columnBitmasks.put("motorcycleYear", 1024L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private LTW_content _escapedModel;

}