/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package ltw.content.service.model.impl;

import ltw.content.service.model.LTW_content;
import ltw.content.service.service.LTW_contentLocalServiceUtil;

/**
 * The extended model base implementation for the LTW_content service. Represents a row in the &quot;LTW_LTW_content&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LTW_contentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LTW_contentImpl
 * @see LTW_content
 * @generated
 */
public abstract class LTW_contentBaseImpl
	extends LTW_contentModelImpl implements LTW_content {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ltw_content model instance should use the <code>LTW_content</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			LTW_contentLocalServiceUtil.addLTW_content(this);
		}
		else {
			LTW_contentLocalServiceUtil.updateLTW_content(this);
		}
	}

}