/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package ltw.content.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the LTW_content service. Represents a row in the &quot;LTW_LTW_content&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>ltw.content.service.model.impl.LTW_contentModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>ltw.content.service.model.impl.LTW_contentImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LTW_content
 * @generated
 */
@ProviderType
public interface LTW_contentModel
	extends BaseModel<LTW_content>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ltw_content model instance should use the {@link LTW_content} interface instead.
	 */

	/**
	 * Returns the primary key of this ltw_content.
	 *
	 * @return the primary key of this ltw_content
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ltw_content.
	 *
	 * @param primaryKey the primary key of this ltw_content
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this ltw_content.
	 *
	 * @return the uuid of this ltw_content
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this ltw_content.
	 *
	 * @param uuid the uuid of this ltw_content
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the ltw ID of this ltw_content.
	 *
	 * @return the ltw ID of this ltw_content
	 */
	public long getLtwId();

	/**
	 * Sets the ltw ID of this ltw_content.
	 *
	 * @param ltwId the ltw ID of this ltw_content
	 */
	public void setLtwId(long ltwId);

	/**
	 * Returns the group ID of this ltw_content.
	 *
	 * @return the group ID of this ltw_content
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this ltw_content.
	 *
	 * @param groupId the group ID of this ltw_content
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this ltw_content.
	 *
	 * @return the company ID of this ltw_content
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this ltw_content.
	 *
	 * @param companyId the company ID of this ltw_content
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this ltw_content.
	 *
	 * @return the user ID of this ltw_content
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this ltw_content.
	 *
	 * @param userId the user ID of this ltw_content
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this ltw_content.
	 *
	 * @return the user uuid of this ltw_content
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this ltw_content.
	 *
	 * @param userUuid the user uuid of this ltw_content
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this ltw_content.
	 *
	 * @return the user name of this ltw_content
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this ltw_content.
	 *
	 * @param userName the user name of this ltw_content
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this ltw_content.
	 *
	 * @return the create date of this ltw_content
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this ltw_content.
	 *
	 * @param createDate the create date of this ltw_content
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this ltw_content.
	 *
	 * @return the modified date of this ltw_content
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this ltw_content.
	 *
	 * @param modifiedDate the modified date of this ltw_content
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the motorcycle name of this ltw_content.
	 *
	 * @return the motorcycle name of this ltw_content
	 */
	@AutoEscape
	public String getMotorcycleName();

	/**
	 * Sets the motorcycle name of this ltw_content.
	 *
	 * @param motorcycleName the motorcycle name of this ltw_content
	 */
	public void setMotorcycleName(String motorcycleName);

	/**
	 * Returns the motorcycle manufacturing of this ltw_content.
	 *
	 * @return the motorcycle manufacturing of this ltw_content
	 */
	@AutoEscape
	public String getMotorcycleManufacturing();

	/**
	 * Sets the motorcycle manufacturing of this ltw_content.
	 *
	 * @param motorcycleManufacturing the motorcycle manufacturing of this ltw_content
	 */
	public void setMotorcycleManufacturing(String motorcycleManufacturing);

	/**
	 * Returns the motorcycle year of this ltw_content.
	 *
	 * @return the motorcycle year of this ltw_content
	 */
	public int getMotorcycleYear();

	/**
	 * Sets the motorcycle year of this ltw_content.
	 *
	 * @param motorcycleYear the motorcycle year of this ltw_content
	 */
	public void setMotorcycleYear(int motorcycleYear);

	@Override
	public LTW_content cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}